### ISSUE TITLE
npm start does not work

### ISSUE THREAD

**Issue by senzacionale** [ethereumproject/TokenMint#70]
There is a bug with npm start

```
$ npm start

> TokenMint@0.1.0 start D:\_ETH\TokenMint
> react-scripts start

D:\_ETH\TokenMint\node_modules\react-scripts\scripts\start.js:33
const {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! TokenMint@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the TokenMint@0.1.0 start script 'react-scripts start'.
npm ERR! This is most likely a problem with the TokenMint package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs TokenMint
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls TokenMint
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\_ETH\TokenMint\npm-debug.log

```

**Comment by senzacionale** [comment]
fixed. used last version of nodejs!
